---
ID: "f9c4ec6a-4df4-4263-a2f5-df88166ecd40"
Parent: "0eb5eff2-57bd-470e-bfd0-be4cc489686f"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Habitat Sites/Habitat/Presentation/Rendering Variants/Title/Default
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{7281C081-4783-419D-B526-30B35CF604CD}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171027T152250Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
