---
ID: "6b95e46b-f8e7-407b-8d52-b8a8c1907359"
Parent: "b63cb28e-37e1-4aac-92e8-b190b491ad5b"
Template: "b63cb28e-37e1-4aac-92e8-b190b491ad5b"
Path: /sitecore/templates/Feature/Habitat Home/XA/Locations/Location/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191004T210019Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "c9e26718-dbba-4f6f-a5f4-f98a2fc2e3ff"
      Hint: Name
      Value: $name
