trigger:
  branches:
    include:
    - feature/*
    - bug/*
    exclude:
    - main
    - develop
    - release/*

pool:
  name: 'Docker-Platform'

stages:
  - stage: Cruise_Build
    jobs:
    - job: Build_Solution
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'docker-registry'
            repository: 'sitecoredemo'
            command: 'build'
            Dockerfile: '**/Dockerfile.cruise'
            arguments: '--build-arg REGISTRY=sitecoredemocontainers.azurecr.io/ --build-arg SITECORE_VERSION=10.0.0 --build-arg INTERNAL_NUGET_SOURCE=$(INTERNAL_NUGET_SOURCE) --build-arg SYSTEM_ACCESSTOKEN=$(System.AccessToken) --isolation hyperv'

