trigger:
  branches:
    include:
    - master
    - release/*
pool:
  name: DEVDEMO1US1
  demands:
  - msbuild
  - azureps
steps:
- task: 4tecture.BuildVersioning.BuildVersioning.BuildVersioning@0
  displayName: 'Set Version Number'
  inputs:
    versionSource: variable
    customNumberVariable: sitecore.version
    paramOverwriteFourthDigitWithBuildCounter: true
    buildNumberAction: replace

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: HabitatHome.TDS.sln
    feedsToUse: config
    nugetConfigPath:  '$(nuget.config)'

- task: MSBuild@1
  displayName: 'HabitatHome - CM'
  inputs:
    solution: HabitatHome.TDS.sln
    configuration: 'Package-CM'
    msbuildArguments: '/m /p:WebDeployPackageName=HabitatHome-CM-$(BuildVersion.Version) /p:PackageName=HabitatHome-CM-$(BuildVersion.Version) /p:SitecoreAssemblyPath=C:\assets\SitecoreLib'

- task: MSBuild@1
  displayName: 'HabitatHome - CD'
  inputs:
    solution: HabitatHome.TDS.sln
    configuration: 'Package-CD'
    msbuildArguments: '/m /p:WebDeployPackageName=HabitatHome-CD-$(BuildVersion.Version) /p:PackageName=HabitatHome-CD-$(BuildVersion.Version)'

- task: PowerShell@2
  displayName: "Convert CM .update packge to scwdp"
  inputs:
    targetType: 'inline'
    script: |
      $sat = "c:\assets\sat\tools\Sitecore.Cloud.Cmdlets.dll"
      Import-Module $sat -Force
      $updatePackageSource = (Get-ChildItem (Join-Path $(Build.SourcesDirectory) "\src\Build\Build.Website\tds\master\bin\") -Filter  HabitatHome-CM*.update -Recurse).FullName 
      ConvertTo-SCModuleWebDeployPackage -Path "$updatePackageSource"  -Destination $(Build.ArtifactStagingDirectory)\temp -Verbose -Force

- task: PowerShell@2
  displayName: "Convert CD .update (files) package to scwdp"
  inputs:
    targetType: 'inline'
    script: |
      $sat = "c:\assets\sat\tools\Sitecore.Cloud.Cmdlets.dll"
      Import-Module $sat -Force
      
      $updatePackageSource = (Get-ChildItem (Join-Path $(Build.SourcesDirectory) "\src\Build\Build.Website\tds\master\bin\") -Filter  HabitatHome-CD*.files.update -Recurse).FullName 
      ConvertTo-SCModuleWebDeployPackage -Path "$updatePackageSource"  -Destination $(Build.ArtifactStagingDirectory)\temp -Verbose -Force

- task: ExtractFiles@1
  displayName: 'Extract CM WDP'
  inputs:
    archiveFilePatterns: '$(Build.ArtifactStagingDirectory)\temp\HabitatHome-CM*.scwdp.zip'
    destinationFolder: '$(Build.ArtifactStagingDirectory)\CM-temp'
    cleanDestinationFolder: true

- task: ExtractFiles@1
  displayName: 'Extract CD WDP'
  inputs:
    archiveFilePatterns: '$(Build.ArtifactStagingDirectory)\temp\HabitatHome-CD*.scwdp.zip'
    destinationFolder: '$(Build.ArtifactStagingDirectory)\CD-temp'
    cleanDestinationFolder: true

- task: CopyFiles@2
  displayName: 'Copy CM Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\Build\Build.Website\tds\master\bin\'
    Contents: |
      **/HabitatHome-CM*.update
      **/HabitatHome-CM*.sccpl
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: CopyFiles@2
  displayName: 'Copy CD Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\Build\Build.Website\tds\master\bin\'
    Contents: |
      **/HabitatHome-CD*.files.update
      **/HabitatHome-CD*.sccpl
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: CopyFiles@2
  displayName: 'Copy Transforms to CM'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: 'HabitatHome-CM*.sccpl'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\CM-temp\Content\Website\App_Data\Transforms'
    flattenFolders: true

- task: CopyFiles@2
  displayName: 'Copy Transforms to CD'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: 'HabitatHome-CD*.sccpl'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\CD-temp\Content\Website\App_Data\Transforms'
    flattenFolders: true

- task: ArchiveFiles@2
  displayName: 'Create defaults scwdp for CM'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\CM-temp'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/HabitatHome-CM-$(BuildVersion.Version).scwdp.zip'
    replaceExistingArchive: true

- task: ArchiveFiles@2
  displayName: 'Create defaults scwdp for CD'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\CD-temp'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/HabitatHome-CD-$(BuildVersion.Version).scwdp.zip'
    replaceExistingArchive: true

- task: DeleteFiles@1
  displayName: 'Delete all temporary folders'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '*temp*'

- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    artifactName: WDPs
    targetPath: '$(Build.ArtifactStagingDirectory)'

- task: AzureFileCopy@2
  displayName: 'AzureBlob File Copy'
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)'
    azureSubscription: AzureSubscription
    Destination: AzureBlob
    storage: sitecoredemopackages
    ContainerName: habitathomeplatform
    BlobPrefix: 'HabitatHome-$(BuildVersion.Version)'

