version: '2.4'

# use docker-compose build

services:

  # sql:
  #   image: ${ACR}sitecore-xp-sqldev:9.2.0-windowsservercore-${WINDOWSSERVERCORE_CHANNEL}
  #   volumes:
  #     - .\data\sql:C:\Data
  #   mem_limit: 2GB
  #   ports:
  #     - "44010:1433"

  sql:
    image: habitathome-xp.sqldev.local
    build:
      context: .\Componentized\Docker\windows\9.2.0 rev. 002893\habitathome-xp.sqldev.local
      dockerfile: dockerfile
    volumes:
      - .\data\sql:C:\Data
    mem_limit: 2GB
    ports:
      - "44010:1433"

  solr:
    image: ${ACR}sitecore-xp-solr:9.2.0-nanoserver-${NANOSERVER_CHANNEL}
    volumes:
      - .\data\solr:C:\Data
    mem_limit: 1GB
    ports:
      - "44011:8983"

  xconnect:
    image: ${ACR}sitecore-xp-xconnect:9.2.0-windowsservercore-${WINDOWSSERVERCORE_CHANNEL}
    volumes:
      - .\data\xconnect:C:\inetpub\xconnect\App_Data\logs
    mem_limit: 1GB
    links:
      - sql
      - solr

  xconnect-automationengine:
    image: ${ACR}sitecore-xp-xconnect-automationengine:9.2.0-windowsservercore-${WINDOWSSERVERCORE_CHANNEL}
    volumes:
      - .\data\xconnect-automationengine:C:\AutomationEngine\App_Data\logs
    mem_limit: 500MB
    links:
      - sql
      - xconnect

  xconnect-indexworker:
    image: ${ACR}sitecore-xp-xconnect-indexworker:9.2.0-windowsservercore-${WINDOWSSERVERCORE_CHANNEL}
    volumes:
      - .\data\xconnect-indexworker:C:\IndexWorker\App_Data\logs
    mem_limit: 500MB
    links:
      - sql
      - solr

  # cd:
  #   image: ${ACR}sitecore-xp-cd:9.2.0-windowsservercore-${WINDOWSSERVERCORE_CHANNEL}
  #   volumes:
  #     - .\data\cd:C:\inetpub\sc\App_Data\logs
  #     - .\Publish\Web:C:\src
  #   ports:
  #     - "44002:80"
  #   links:
  #     - sql
  #     - solr
  #     - xconnect
  #   entrypoint: cmd /c "powershell C:/Sitecore/Scripts/Watch-Directory.ps1 C:/src C:\inetpub\sc -ExcludeFiles @('Web.config','ConnectionStrings.config')"

  cm:
    image: ${ACR}sitecore-xp-standalone:9.2.0-windowsservercore-${WINDOWSSERVERCORE_CHANNEL}
    volumes:
      - .\data\cm:C:\inetpub\sc\App_Data\logs
      - .\Publish\Web:C:\src
      - C:\Deploy\Habitat.Platform\yml:c:\unicorn\ # to-do yml from src folder, and set unicorn sourceFolder to c:\unicorn 
    ports:
      - "44001:80"
    links:
      - sql
      - solr
      - xconnect
    entrypoint: cmd /c "powershell C:/Sitecore/Scripts/Watch-Directory.ps1 C:/src C:\inetpub\sc -ExcludeFiles @('Web.config','ConnectionStrings.config', 'System.Buffers.dll')"
