apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd
  labels:
    app: cd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cd
  template:
    metadata:
      labels:
        app: cd
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: cd
        image: sitecore-xm1-cd:9.1.1-windowsservercore-ltsc2019
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: .1
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cd
  labels:
    app: cd
spec:
  selector:
    app: cd
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
