apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm
  labels:
    app: cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm
  template:
    metadata:
      labels:
        app: cm
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: cm
        image: sitecore-xm1-cm:9.1.1-windowsservercore-ltsc2019
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: .1
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cm
  labels:
    app: cm
spec:
  selector:
    app: cm
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
