apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
  labels:
    app: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: solr
        image: sitecore-xm1-solr:9.1.1-nanoserver-1809
        ports:
          - containerPort: 8983
        resources:
          limits:
            cpu: 2
            memory: 1500Mi
          requests:
            cpu: .1
            memory: 500Mi
        volumeMounts:
          - mountPath: "/data"
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: solr-data
---
apiVersion: v1
kind: Service
metadata:
  name: solr
  labels:
    app: solr
spec:
  selector:
    app: solr
  type: ClusterIP
  ports:
   - name: http
     targetPort: 8983
     port: 8983
