---
ID: "80ca64a8-e561-452f-b5f0-2ec1bcc0df75"
Parent: "01171516-42eb-4cbe-b2eb-f02c58e1d7bd"
Template: "9e5634a8-c7ca-4076-a6d0-3f3a6fa19646"
Path: /sitecore/content/SFMC Tenant/Tenant Settings/Providers/SFMC/Parameters
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{80CA64A8-E561-452F-B5F0-2EC1BCC0DF75}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200406T163725Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
