---
ID: "5eb100ce-c479-4e6f-b296-90798aaa2716"
Parent: "013c82e4-a7ee-4e14-84e4-5970f5a69cc1"
Template: "013c82e4-a7ee-4e14-84e4-5970f5a69cc1"
Path: /sitecore/templates/Project/Habitat SXA Sites/Habitat Home/Landing Pages/Careers Landing Page/__Standard Values
DB: master
Created: 20191004T205125Z
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{6EC40BE2-7F7E-486A-9774-233907150786}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191004T205125Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6298c2ae-4db6-47ba-9f03-b45ce4c6ab14"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20191004T205156Z
