---
ID: "7cb32815-0033-402b-b527-1c1317b076cc"
Parent: "51262c67-e9ce-49d2-bdd5-1262eeea23d8"
Template: "51262c67-e9ce-49d2-bdd5-1262eeea23d8"
Path: /sitecore/templates/Project/Habitat SXA Sites/Habitat Home/Landing Pages/Guides Landing Page/__Standard Values
DB: master
Created: 20191025T151030Z
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{14807D83-9671-4D70-B0F4-F54012F2BFB8}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191025T151030Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b4fb18a1-7c7a-4ec2-905d-2c7c102b97ab"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20191025T151058Z
