---
ID: "825f6e78-d41a-4150-bde7-2d4971b5f3ae"
Parent: "d106699b-72b1-49c8-be68-e9c9f103ae85"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Habitat SXA Sites/Sitecore Demo/Presentation/Rendering Variants/POI/Default
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{09180CD8-3CA2-4A92-B3B5-F4F057BA465C}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190921T114833Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
