---
ID: "6b6b0190-2702-46ab-a2c4-d72e05d42a1c"
Parent: "ed2c48eb-0015-401b-bee2-17e8389ac60e"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Habitat Sites/Habitat/Presentation/Rendering Variants/Link/Default
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{D9F3C5DF-05F7-48EE-AD81-53956BDFA605}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171027T152149Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
