---
ID: "a6785368-25bc-467e-9337-e7fc90686059"
Parent: "48c3ca43-d20a-42e8-b618-4e95641673f5"
Template: "48c3ca43-d20a-42e8-b618-4e95641673f5"
Path: /sitecore/templates/Project/Habitat SXA Sites/Habitat Home/Landing Pages/Events Landing Page/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{9B87D09A-3A73-4E0A-8EE8-C192719D256F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190927T201607Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
