---
ID: "16d2c174-4767-4870-aecb-dd165550cab5"
Parent: "635cff0a-9bdf-41c8-b04e-66788a626218"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Habitat SXA Sites/Sitecore Demo/Presentation/Rendering Variants/Promo/Default
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{5DF9B10F-F5B5-4E6A-AD58-08125A701147}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190921T114900Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
