---
ID: "855266f5-d1f5-48cd-bd0c-142f89a57f9c"
Parent: "9f81ffb2-dae7-4907-a37e-43682a93103a"
Template: "9f81ffb2-dae7-4907-a37e-43682a93103a"
Path: /sitecore/templates/Feature/Habitat Home/XA/Careers/Job Type Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{E507AF79-D40E-43CC-93E0-CE725FD82CDD}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190919T181414Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
