---
ID: "5fe424f0-49ab-4a1c-a1e9-998e810d4119"
Parent: "8ed0772e-005a-4184-93fa-aaf64a3b7172"
Template: "e2f11ae2-6c89-411c-879f-9ffbcab98c90"
Path: /sitecore/content/Salesforce CRM Tenant/Pipelines/Salesforce Campaigns to xConnect Sync Pipelines/Read Campaigns from Salesforce/Set Use Delta Settings
DB: master
BranchID: "200ef76c-dd0f-4845-9863-b0d4ee1eb36f"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
- ID: "cac1d3bf-041f-46e8-abe1-74701e54554e"
  Hint: ContextValueReader
  Value: "{23B525C8-B9D0-4E3D-8192-DAAB2D4C5B15}"
- ID: "cba1e09b-2b35-4165-a7f8-6300e7bce2b5"
  Hint: Operator
  Value: OnOrAfterSelectedDate
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{5FE424F0-49AB-4A1C-A1E9-998E810D4119}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210111T115507Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
