---
ID: "9dcb91df-aefb-4d97-9581-6c25cfcd859d"
Parent: "9e655297-b109-4673-acb8-d661c9007736"
Template: "9e655297-b109-4673-acb8-d661c9007736"
Path: /sitecore/templates/Project/Habitat SXA Sites/Habitat Home/Pages/Blog Page/__Standard Values
DB: master
Created: 20191003T173037Z
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{BCFC7537-EFF4-434C-96F5-BF4F55FD175B}">
        <r
          ds=""
          id="{BFBD9DE2-3ABF-4078-BBCB-C95C5B2D863F}"
          par="GridParameters&amp;FieldNames&amp;Styles&amp;BreadcrumbRoot&amp;Separator=%3E&amp;IsNavigation&amp;Filter&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=2"
          ph="/main/sxa-news-content/author-1-/container-3"
          uid="{450FE23A-66BE-44C8-839F-92BB354A0464}" />
        <r
          ds=""
          id="{0FA50A16-13DF-4722-9357-C7D157638ACA}"
          par="GridParameters&amp;FieldNames&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=1"
          ph="/main/sxa-news-content/author-1-/container-4"
          uid="{8FF56C69-FFDB-4AEE-8DE0-4FF4F223FBDF}" />
      </d>
      <d
        id="{0B4A31C9-712D-4578-A396-2DDC0F34B63A}"
        l="{72C595AD-68BB-44BC-B5CD-2A857039515F}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{8FF56C69-FFDB-4AEE-8DE0-4FF4F223FBDF}"
              s:par="GridParameters&amp;FieldNames=%7B20913714-087C-4699-8AD2-5AD733AC09F4%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=1" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191003T173037Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eb961c38-8961-42b5-83db-d4abdbf024a3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20191010T145717Z
