---
ID: "f396192c-be80-40cb-876a-65bfa8f858d5"
Parent: "8ab33e76-a119-4c8b-8d11-cfb9a61ad741"
Template: "8ab33e76-a119-4c8b-8d11-cfb9a61ad741"
Path: /sitecore/templates/Project/Habitat SXA Sites/Habitat Home/Landing Pages/Resources Landing Page/__Standard Values
DB: master
Created: 20191004T000017Z
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{F38211F9-F685-44C7-9A97-3D34AB7FE66B}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191004T000017Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b93338a5-540f-42fc-8276-d274a8d2e166"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20191004T000048Z
