---
ID: "5e255ec8-0321-4730-9b0d-e31527b97eca"
Parent: "e507af79-d40e-43cc-93e0-ce725fd82cdd"
Template: "e507af79-d40e-43cc-93e0-ce725fd82cdd"
Path: /sitecore/templates/Feature/Habitat Home/XA/Careers/Job Type/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190919T182759Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7ed012be-a963-4e49-b9ec-79d6974f6821"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "c59e02e1-1d56-4fee-b7c5-03279188306c"
      Hint: Title
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190919T182804Z
