---
ID: "ba477474-6ef5-46a5-971f-cb32d17e1856"
Parent: "f42cb279-a2e3-48d6-a3c4-b3d252b50e95"
Template: "f42cb279-a2e3-48d6-a3c4-b3d252b50e95"
Path: /sitecore/templates/Project/Habitat SXA Sites/Habitat Home/Landing Pages/News Landing Page/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{CA3168E9-2E1C-443D-A7C8-9C17F7517562}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190927T201607Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c0759b1b-b91a-47b8-ab1c-1558105fdcde"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190927T201633Z
