---
ID: "46c4372f-c8b3-4d7e-b79c-12c9d3b1d153"
Parent: "568d0b5c-eccb-4a2f-a301-79c7761cda36"
Template: "568d0b5c-eccb-4a2f-a301-79c7761cda36"
Path: /sitecore/templates/Project/Habitat Sites/Demo Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171108T144102Z
