---
ID: "ca6265a9-8fef-44d4-8f80-3472baae795b"
Parent: "27b086e4-9c0c-497e-8aa7-c4c9541afab7"
Template: "0a2847e6-9885-450b-b61e-f9e6528480ef"
Path: /sitecore/system/Dictionary/Project/Demo Shared SXA Sites/SitecoreDemo/Coveo Indexing Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210106T170133Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\superuser
