---
ID: "4876a0e8-3f79-4b93-bc23-61e7fc5dfcc5"
Parent: "1e5bfa08-0e32-4156-927e-930392fdcb92"
Template: "1e5bfa08-0e32-4156-927e-930392fdcb92"
Path: /sitecore/templates/Project/Habitat Sites/Common/Settings/Security Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171206T135015Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
