---
ID: "beceb30c-fa7f-4b7b-9973-728fbf4bc8ec"
Parent: "16c23e6a-7437-4102-b611-86048f840dae"
Template: "759faf75-ea5f-4ede-bbc2-365f19851b21"
Path: /sitecore/content/Salesforce CRM Tenant/Tenant Settings/Providers/xConnect/XObject Mapping Settings
DB: master
BranchID: "200ef76c-dd0f-4845-9863-b0d4ee1eb36f"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{BECEB30C-FA7F-4B7B-9973-728FBF4BC8EC}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210111T115517Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
