---
ID: "6c059675-9f56-4b28-a61e-6374cd930d7f"
Parent: "2011de0a-1280-4d0b-9b1e-202c659aaf04"
Template: "2011de0a-1280-4d0b-9b1e-202c659aaf04"
Path: /sitecore/templates/Project/Habitat SXA Sites/Habitat Home/Landing Pages/News and Events Landing Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190927T210040Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
