---
ID: "6c059675-9f56-4b28-a61e-6374cd930d7f"
Parent: "2011de0a-1280-4d0b-9b1e-202c659aaf04"
Template: "2011de0a-1280-4d0b-9b1e-202c659aaf04"
Path: /sitecore/templates/Project/Habitat SXA Sites/Habitat Home/Landing Pages/News and Events Landing Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190927T210040Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bf06da52-2ee2-4443-81da-3bc9f57d323b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190927T210040Z
