---
ID: "e8ed47dc-c32e-4930-9134-daed8ee5ce7a"
Parent: "cc4b2131-e59f-466b-9290-17650dbbd145"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Habitat SXA Sites/Sitecore Demo/Presentation/Rendering Variants/Event List/Default
DB: master
SharedFields:
- ID: "90294353-706a-431c-b855-cd245824d9fa"
  Hint: LinkField
  Value: File
- ID: "e1d5adba-8348-4127-9bb6-455936653839"
  Hint: CssClass
  Value: "file-type-icon-media-link"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{B046ABD0-0158-404C-AF4F-E924703B7227}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190921T114823Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
