---
ID: "ebd498ba-a204-41e3-953d-94ced6cf775f"
Parent: "8dcecf0c-80bf-4a34-af29-45f5f1463399"
Template: "1a7d9344-df9d-4605-99d8-4d752a9edb2f"
Path: /sitecore/content/Habitat Corporate/Settings
DB: master
SharedFields:
- ID: "6d85d254-3f84-4a22-9d29-61832b08df2d"
  Hint: Logo
  Value: |
    <image mediaid="{90D766AA-C55E-4393-94ED-63854FD8C30A}" />
Languages:
- Language: en
  Fields:
  - ID: "2a84eca4-68bb-4451-b4ac-98ea71a5a3dc"
    Hint: SiteProfiles
    Type: Multilist
    Value: "{B5BDEE45-C945-476F-9EE6-3B8A9255C17E}"
  Versions:
  - Version: 1
    Fields:
    - ID: "202eaae4-33b3-4db1-9170-4de88a27e7cd"
      Hint: User Profile
      Value: "{BCBF635A-9C02-4EFE-85FB-19358FAEAAB2}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190104T132841Z
    - ID: "81b370b0-9ea6-435d-be15-fcffb1cec57f"
      Hint: Register Page
      Value: /sitecore/content/Habitat Corporate/Home/Register
    - ID: "9cb71d9c-0785-4f9b-95cd-74c3becf9da2"
      Hint: Title
      Value: Habitat Corporate
    - ID: "e90c6342-5bc9-4011-a3c5-eed1fca7eb7c"
      Hint: Login Page
      Value: /sitecore/content/Habitat Corporate/Home/Login
